# Generated by Django 4.1.10 on 2023-07-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
