# Generated by Django 4.1.10 on 2023-07-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_author_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
